name: cates
favicon: null
layout_spectrum: 0.72509
typography_spectrum: 0.77306
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3a65a9'
    - '#dcdbd9'
    - '#6085b2'
    - '#94a9c8'
    - '#394e5f'
  brandStrength: 0.3125103674829006
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
